### ISSUE TITLE
Lisans düzenlemesi

### ISSUE THREAD

**Issue by gurayops** [celilileri/lyk2016#3]
Lisans dosyasının kendi sitesinde how-to kısmında sadece lisans dosyasının adı ve birkaç bilginin daha yer almasının diğer yerler için yeterli olduğu yazıyor. Yani notların olduğu dosyaya doğru anladıysam örnekteki kadar bir bilgi yeterli olacak:
https://www.gnu.org/licenses/fdl-howto.html

**Comment by ileri** [comment]
Gerekli dosyalara lisans bilgileri eklenmiş. :+1:
